import { Righteous, Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
subsets: ["latin"],
variable: "--font-poppins",
weight: ["100", "200" , "300", "400", "500", "600", "700", "800", "900" ]
})

export const metadata = {
  title: "Hassan Naseer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className={`${poppins.variable} `}>
      <body className="antialiased">
        {children}
      </body>
    </html>
    
  );
}
